title: 崔淮冰的每天笔记
author: 崔淮冰
email: huaibingcui@gmail.com
description: > # this means to ignore newlines until "twitter_username:" 
  用GitHub Pages搭建这个Blogs网站，并通过Jekyll在Markdown写作后自动生成页面。
# Here is my individual platform where
# I share one learning experience, insight, or lesson every single day. 
# The goal is to
# inspire continuous growth and document my journey of knowledge.

# URL 设置
# 如果你的网站不是部署在域名根目录，请设置 baseurl
# 例如：如果你的网站是 https://username.github.io/repository-name/
# 那么 baseurl 应该是 "/repository-name"
baseurl: "" # 如果部署在根目录，保持为空
url: "https://hbcui.github.io" # 你的网站 URL，例如 "https://hbcui.github.io"

# social links
# twitter_username: jekyllrb
github_username:  jekyll
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # abstract in home page, set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y年%m月%d日"
# date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
